apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-demo
  namespace: hazelcast-demo-dev
  labels:
    app: hazelcast-demo
    version: v1.1.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hazelcast-demo
  template:
    metadata:
      labels:
        app: hazelcast-demo
        version: v1.1.0
    spec:
      serviceAccountName: hazelcast-service-account
      containers:
      - name: hazelcast-demo
        image: hazelcast-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 5701
          name: hazelcast
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 12
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "openshift-local"
        - name: SERVER_PORT
          value: "8080"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_HOST
          value: "postgresql"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "hazelcastdb"
        - name: DB_USERNAME
          value: "hazelcast"
        - name: DB_PASSWORD
          value: "hazelcast123"
        - name: HAZELCAST_SERVICE_NAME
          value: "hazelcast-demo-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-demo-service
  namespace: hazelcast-demo-dev
  labels:
    app: hazelcast-demo
spec:
  selector:
    app: hazelcast-demo
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 5701
    targetPort: 5701
    protocol: TCP
    name: hazelcast
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast-service-account
  namespace: hazelcast-demo-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hazelcast-role
  namespace: hazelcast-demo-dev
rules:
- apiGroups: [""]
  resources: ["pods", "endpoints", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-role-binding
  namespace: hazelcast-demo-dev
subjects:
- kind: ServiceAccount
  name: hazelcast-service-account
  namespace: hazelcast-demo-dev
roleRef:
  kind: Role
  name: hazelcast-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hazelcast-demo-route
  namespace: hazelcast-demo-dev
  labels:
    app: hazelcast-demo
spec:
  to:
    kind: Service
    name: hazelcast-demo-service
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
