apiVersion: apps/v1
kind: Deployment
metadata:
  name: hazelcast-demo
  namespace: contactcenter-dev
  labels:
    app: hazelcast-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hazelcast-demo
  template:
    metadata:
      labels:
        app: hazelcast-demo
        logging: "true"
    spec:
      serviceAccountName: hazelcast-service-account
      containers:
      - name: hazelcast-demo
        image: <your-registry>/hazelcast-demo:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: dbname
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: hazelcast-config
          mountPath: /app/config
      volumes:
      - name: hazelcast-config
        configMap:
          name: hazelcast-config
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-demo-service
  namespace: contactcenter-dev
spec:
  selector:
    app: hazelcast-demo
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hazelcast-config
  namespace: contactcenter-dev
data:
  hazelcast.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <hazelcast xmlns="http://www.hazelcast.com/schema/config"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.hazelcast.com/schema/config
               http://www.hazelcast.com/schema/config/hazelcast-config-5.0.xsd">
        <network>
            <port auto-increment="true">5701</port>
            <join>
                <kubernetes enabled="true">
                    <properties>
                        <property name="namespace">${KUBERNETES_NAMESPACE:default}</property>
                    </properties>
                </kubernetes>
            </join>
        </network>
        <cache name="users">
            <key-type class-name="java.lang.Long"/>
            <value-type class-name="com.example.hazelcastdemo.User"/>
        </cache>
    </hazelcast>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hazelcast-service-account
  namespace: contactcenter-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hazelcast-role
  namespace: contactcenter-dev
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-role-binding
  namespace: contactcenter-dev
subjects:
- kind: ServiceAccount
  name: hazelcast-service-account
  namespace: contactcenter-dev
roleRef:
  kind: Role
  name: hazelcast-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hazelcast-demo-route
  namespace: contactcenter-dev
spec:
  to:
    kind: Service
    name: hazelcast-demo-service
  port:
    targetPort: 8080
