---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: contactcenter-dev
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: False
    auth.anonymous:
      enabled: True
  dashboardLabelSelector:
    - matchLabels:
        app: hazelcast-demo
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: prometheus
  namespace: contactcenter-dev
spec:
  name: prometheus.yaml
  datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-operated:9090
    isDefault: true
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  name: hazelcast-dashboard
  namespace: contactcenter-dev
  labels:
    app: hazelcast-demo
spec:
  json: >
    {
      "dashboard": {
        "id": null,
        "title": "Hazelcast Demo Dashboard",
        "tags": ["hazelcast", "spring-boot", "prometheus"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "JVM Memory Usage",
            "type": "graph",
            "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
            "targets": [
              {
                "expr": "jvm_memory_used_bytes{job=\"hazelcast-demo\"}",
                "legendFormat": "{{area}} - Used"
              }
            ]
          },
          {
            "id": 2,
            "title": "HTTP Request Rate",
            "type": "graph",
            "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
            "targets": [
              {
                "expr": "rate(http_server_requests_seconds_count{job=\"hazelcast-demo\"}[5m])",
                "legendFormat": "{{method}} {{uri}}"
              }
            ]
          }
        ],
        "time": {"from": "now-1h", "to": "now"},
        "refresh": "30s"
      }
    }
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-route
  namespace: contactcenter-dev
spec:
  to:
    kind: Service
    name: grafana-service
  port:
    targetPort: 3000
