# Application Configuration - Staging Environment
# Place this file as: src/main/resources/application-staging.yml

spring:
  profiles:
    active: staging
  datasource:
    url: jdbc:postgresql://${DB_HOST:staging-db}:5432/hazelcastdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

hazelcast:
  network:
    join:
      tcp-ip:
        enabled: true
        members:
          - staging-hazelcast-1:5701
          - staging-hazelcast-2:5701

logging:
  level:
    com.example: INFO
    org.springframework: WARN
