# Application Configuration - Development Environment
# Place this file as: src/main/resources/application-dev.yml

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/hazelcastdb
    username: postgres
    password: dev_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

hazelcast:
  network:
    join:
      multicast:
        enabled: true

logging:
  level:
    com.example: DEBUG
    org.springframework: INFO
