# Application Configuration - Production Environment
# Place this file as: src/main/resources/application-prod.yml

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true

hazelcast:
  network:
    join:
      kubernetes:
        enabled: true
        namespace: ${KUBERNETES_NAMESPACE}
        service-name: hazelcast-demo-service
  map:
    users:
      time-to-live-seconds: 3600
      max-idle-seconds: 1800

logging:
  level:
    com.example: INFO
    org.springframework: WARN
    org.hibernate: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: when-authorized
